### ISSUE TITLE
Site url what

### ISSUE THREAD

**Issue by devashish2024** [anil-turk/FreeGPT-NodeJS-PHP#2]
```js
const site = ""; // your php site url where you get the prompt data and send the response
```
What I input to test local?

**Comment by devashish2024** [comment]
Any idea to host on flask on pythonaywhere as a 24x7 free api? Would be useful for some reason....

**Comment by anil-turk** [comment]
site variable is for the site url (without https://) of that you put example.php file
For example: www.yoursite.com/example.php

And no, unfortunately I don't know anything about flask.
